sponsors:
  - name: Codurance
    url: http://codurance.com/
    logo: codurance.png
  - name: Unruly Media
    url: http:///www.unrulymedia.com/talent
    logo: unruly.png
  - name: Pivotal Labs
    url: http://pivotallabs.com/
    logo: pivotallabs.png
  - name: Mozaic Works
    url: http://www.mozaicworks.com/
    logo: mozaicworks.png
  - name: Novoda
    url: http://novoda.com/
    logo: novoda.png
  - name: Valech
    url: http://valtech.co.uk/
    logo: valtech.jpeg
