sponsors:
  - name: Mozaic Works
    url: http://www.mozaicworks.com/
    logo: mozaicworks.png
  - name: Skills Matter
    url: http://skillsmatter.com/
    logo: skillsmatter.gif
  - name: Unruly Media
    url: http://www.unrulymedia.com/
    logo: unruly.png
