sponsors:
  - name: Unruly Media
    url: http://unruly.co/
    logo: unruly.png
  - name: Argos
    url: http://www.argos.co.uk/
    logo: argos.png
  - name: 8th Light
    url: http://8thlight.com/
    logo: 8th-Light.png